name: CI
'on': push
jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.19.1
          - 15.0.1
    steps:
      - uses: actions/checkout@v4
      - name: 'Build / Test Node ${{ matrix.node-version }}'
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npm ci
      - run: npm run cover --if-present
  release:
    needs:
      - test-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 14.19.1
      - run: npm ci
      - run: npx semantic-release
        env:
          CI: 'true'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
